{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.proxmox.secretName }}
  labels:
    {{- include "proxmox-dns-sync.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.proxmox.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.proxmox.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.proxmox.vaultPath }}
        property: {{ .Values.externalSecrets.proxmox.vaultProperty }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.pihole.secretName }}
  labels:
    {{- include "proxmox-dns-sync.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.pihole.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.pihole.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.pihole.vaultPath }}
        property: {{ .Values.externalSecrets.pihole.vaultProperty }}
{{- end }}
