apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-dns
spec:
  provider:
    vault:
      server: "http://vault.lodge.chalko.com:8200" # Target Vault server URL
      path: "secret"
      version: "v2"
      auth:
        # Standard Kubernetes service account authentication
        kubernetes:
          mountPath: "kubernetes"
          role: "external-dns-secrets-role"
          serviceAccountRef:
            name: external-dns
